//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace 发电信息管理 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class inputSheet : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox stationComBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker losePowerTimePicker;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBox1;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker startGenerationTimePicker;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker stopGenerationTimePicker;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button submitBnt;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox textBox2;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button selectImageBNT;
        
        internal Microsoft.Office.Tools.Excel.Controls.TextBox beforeGenVoltage;
        
        private System.ComponentModel.IContainer components;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public inputSheet(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet1", "Sheet1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.inputSheet = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.stationComBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "134CE1C7D1508E1452F1820E14A904AB6E60B1", "134CE1C7D1508E1452F1820E14A904AB6E60B1", this, "stationComBox");
            this.losePowerTimePicker = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "270C259A32BAD124BB8284F92171AA2BE56432", "270C259A32BAD124BB8284F92171AA2BE56432", this, "losePowerTimePicker");
            this.textBox1 = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "5E1AEB4485A0C454C045BB775CD71E8BF284F5", "5E1AEB4485A0C454C045BB775CD71E8BF284F5", this, "textBox1");
            this.startGenerationTimePicker = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "670A3571666904641496823E60E9F582803BF6", "670A3571666904641496823E60E9F582803BF6", this, "startGenerationTimePicker");
            this.stopGenerationTimePicker = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "9C53E8F269F04F946589A1069DBFA5DE252D99", "9C53E8F269F04F946589A1069DBFA5DE252D99", this, "stopGenerationTimePicker");
            this.submitBnt = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "134542D801BF10143671AAAC1D337FF6475541", "134542D801BF10143671AAAC1D337FF6475541", this, "submitBnt");
            this.textBox2 = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "1DEBE1DD61EF8814DFC19DC51D00A66FA1BFF1", "1DEBE1DD61EF8814DFC19DC51D00A66FA1BFF1", this, "textBox2");
            this.selectImageBNT = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1B19A9D0517A581491F1BF9A19FB082C566271", "1B19A9D0517A581491F1BF9A19FB082C566271", this, "selectImageBNT");
            this.beforeGenVoltage = new Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "168759139108BB14E101887B11F9A9C9A744C1", "168759139108BB14E101887B11F9A9C9A744C1", this, "beforeGenVoltage");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // stationComBox
            // 
            this.stationComBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.stationComBox.DropDownHeight = 300;
            this.stationComBox.IntegralHeight = false;
            this.stationComBox.MaxDropDownItems = 30;
            this.stationComBox.Name = "stationComBox";
            // 
            // losePowerTimePicker
            // 
            this.losePowerTimePicker.CustomFormat = "yyyy/MM/dd HH:mm:ss";
            this.losePowerTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.losePowerTimePicker.Name = "losePowerTimePicker";
            this.losePowerTimePicker.Value = new System.DateTime(2017, 7, 6, 0, 0, 0, 0);
            // 
            // textBox1
            // 
            this.textBox1.Name = "textBox1";
            // 
            // startGenerationTimePicker
            // 
            this.startGenerationTimePicker.CustomFormat = "yyyy/MM/dd HH:mm:ss";
            this.startGenerationTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.startGenerationTimePicker.Name = "startGenerationTimePicker";
            this.startGenerationTimePicker.Value = new System.DateTime(2017, 7, 6, 0, 0, 0, 0);
            // 
            // stopGenerationTimePicker
            // 
            this.stopGenerationTimePicker.CustomFormat = "yyyy/MM/dd HH:mm:ss";
            this.stopGenerationTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.stopGenerationTimePicker.Name = "stopGenerationTimePicker";
            this.stopGenerationTimePicker.Value = new System.DateTime(2017, 7, 6, 0, 0, 0, 0);
            // 
            // submitBnt
            // 
            this.submitBnt.BackColor = System.Drawing.SystemColors.Control;
            this.submitBnt.ForeColor = System.Drawing.SystemColors.ControlText;
            this.submitBnt.Name = "submitBnt";
            this.submitBnt.Text = "提交";
            this.submitBnt.UseVisualStyleBackColor = false;
            // 
            // textBox2
            // 
            this.textBox2.Name = "textBox2";
            // 
            // selectImageBNT
            // 
            this.selectImageBNT.BackColor = System.Drawing.SystemColors.Control;
            this.selectImageBNT.ForeColor = System.Drawing.SystemColors.ControlText;
            this.selectImageBNT.Name = "selectImageBNT";
            this.selectImageBNT.Text = "选择图片目录";
            this.selectImageBNT.UseVisualStyleBackColor = false;
            // 
            // beforeGenVoltage
            // 
            this.beforeGenVoltage.Name = "beforeGenVoltage";
            this.beforeGenVoltage.Text = "48.2";
            // 
            // inputSheet
            // 
            this.stationComBox.BindingContext = this.BindingContext;
            this.losePowerTimePicker.BindingContext = this.BindingContext;
            this.textBox1.BindingContext = this.BindingContext;
            this.startGenerationTimePicker.BindingContext = this.BindingContext;
            this.stopGenerationTimePicker.BindingContext = this.BindingContext;
            this.submitBnt.BindingContext = this.BindingContext;
            this.textBox2.BindingContext = this.BindingContext;
            this.selectImageBNT.BindingContext = this.BindingContext;
            this.beforeGenVoltage.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static inputSheet _inputSheet;
        
        internal static inputSheet inputSheet {
            get {
                return _inputSheet;
            }
            set {
                if ((_inputSheet == null)) {
                    _inputSheet = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
