//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace 发电信息管理 {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(2)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class outputReport : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button dailyReportBNT;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker reportStartTimePick;
        
        internal Microsoft.Office.Tools.Excel.Controls.DateTimePicker reportEndTimePicker;
        
        internal Microsoft.Office.Tools.Excel.Controls.ComboBox templetComBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button reflashTempletBNT;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox setSumTable;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox IsGetTelecomDatacheckBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox IsGetMobileDatacheckBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox IsGetUnicomDatacheckBox;
        
        internal Microsoft.Office.Tools.Excel.Controls.CheckBox IsGetNotRequireStationcheckBox;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public outputReport(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet5", "Sheet5") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.outputReport = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.dailyReportBNT = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1BDC0F6BE1A7041452C19F5212306949B62A71", "1BDC0F6BE1A7041452C19F5212306949B62A71", this, "dailyReportBNT");
            this.reportStartTimePick = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "2BB5540C62C0E8242372BBDC2E0A31D2E57C12", "2BB5540C62C0E8242372BBDC2E0A31D2E57C12", this, "reportStartTimePick");
            this.reportEndTimePicker = new Microsoft.Office.Tools.Excel.Controls.DateTimePicker(Globals.Factory, this.ItemProvider, this.HostContext, "42E12A31E4C7144472D4821645860DA4BD9AA4", "42E12A31E4C7144472D4821645860DA4BD9AA4", this, "reportEndTimePicker");
            this.templetComBox = new Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, this.ItemProvider, this.HostContext, "59C6BA0B7563585489358FAD591C3DD145F455", "59C6BA0B7563585489358FAD591C3DD145F455", this, "templetComBox");
            this.reflashTempletBNT = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6E3DA1F3D61BDA64ADC6915267F6C19E2026B6", "6E3DA1F3D61BDA64ADC6915267F6C19E2026B6", this, "reflashTempletBNT");
            this.setSumTable = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8FB135ED684C05841ED8A3DC89D87804DABCF8", "8FB135ED684C05841ED8A3DC89D87804DABCF8", this, "setSumTable");
            this.IsGetTelecomDatacheckBox = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "96FE580379A48A944AD9946C9CE706199D3AC9", "96FE580379A48A944AD9946C9CE706199D3AC9", this, "IsGetTelecomDatacheckBox");
            this.IsGetMobileDatacheckBox = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "13879C08B148CB1433C1B31E12AE652E062691", "13879C08B148CB1433C1B31E12AE652E062691", this, "IsGetMobileDatacheckBox");
            this.IsGetUnicomDatacheckBox = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1B8396BD5176F3148921A02015A2F460449691", "1B8396BD5176F3148921A02015A2F460449691", this, "IsGetUnicomDatacheckBox");
            this.IsGetNotRequireStationcheckBox = new Microsoft.Office.Tools.Excel.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1402C885A12EE4141BA1B6DE11A512A3DBE191", "1402C885A12EE4141BA1B6DE11A512A3DBE191", this, "IsGetNotRequireStationcheckBox");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "15.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // dailyReportBNT
            // 
            this.dailyReportBNT.BackColor = System.Drawing.SystemColors.Control;
            this.dailyReportBNT.ForeColor = System.Drawing.SystemColors.ControlText;
            this.dailyReportBNT.Name = "dailyReportBNT";
            this.dailyReportBNT.Text = "生成报表";
            this.dailyReportBNT.UseVisualStyleBackColor = false;
            // 
            // reportStartTimePick
            // 
            this.reportStartTimePick.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.reportStartTimePick.Name = "reportStartTimePick";
            this.reportStartTimePick.Value = new System.DateTime(2017, 7, 10, 0, 0, 0, 0);
            // 
            // reportEndTimePicker
            // 
            this.reportEndTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.reportEndTimePicker.Name = "reportEndTimePicker";
            // 
            // templetComBox
            // 
            this.templetComBox.FlatStyle = System.Windows.Forms.FlatStyle.System;
            this.templetComBox.Items.AddRange(new object[] {
                        "日报表模板",
                        "电信周报模板",
                        "移动周报表模板",
                        "联通周报模板",
                        "自定义模板"});
            this.templetComBox.Name = "templetComBox";
            this.templetComBox.Text = "日报表模板";
            // 
            // reflashTempletBNT
            // 
            this.reflashTempletBNT.BackColor = System.Drawing.SystemColors.Control;
            this.reflashTempletBNT.ForeColor = System.Drawing.SystemColors.ControlText;
            this.reflashTempletBNT.Name = "reflashTempletBNT";
            this.reflashTempletBNT.Text = "刷新模板";
            this.reflashTempletBNT.UseVisualStyleBackColor = false;
            // 
            // setSumTable
            // 
            this.setSumTable.Name = "setSumTable";
            this.setSumTable.Text = "是否生成汇总表";
            // 
            // IsGetTelecomDatacheckBox
            // 
            this.IsGetTelecomDatacheckBox.Checked = true;
            this.IsGetTelecomDatacheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.IsGetTelecomDatacheckBox.Name = "IsGetTelecomDatacheckBox";
            this.IsGetTelecomDatacheckBox.Text = "是否包含电信站点";
            // 
            // IsGetMobileDatacheckBox
            // 
            this.IsGetMobileDatacheckBox.Checked = true;
            this.IsGetMobileDatacheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.IsGetMobileDatacheckBox.Name = "IsGetMobileDatacheckBox";
            this.IsGetMobileDatacheckBox.Text = "是否包含移动站点";
            // 
            // IsGetUnicomDatacheckBox
            // 
            this.IsGetUnicomDatacheckBox.Checked = true;
            this.IsGetUnicomDatacheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.IsGetUnicomDatacheckBox.Name = "IsGetUnicomDatacheckBox";
            this.IsGetUnicomDatacheckBox.Text = "是否包含联通站点";
            // 
            // IsGetNotRequireStationcheckBox
            // 
            this.IsGetNotRequireStationcheckBox.Checked = true;
            this.IsGetNotRequireStationcheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.IsGetNotRequireStationcheckBox.Name = "IsGetNotRequireStationcheckBox";
            this.IsGetNotRequireStationcheckBox.Text = "是否包含不要求发电站点";
            // 
            // outputReport
            // 
            this.dailyReportBNT.BindingContext = this.BindingContext;
            this.reportStartTimePick.BindingContext = this.BindingContext;
            this.reportEndTimePicker.BindingContext = this.BindingContext;
            this.templetComBox.BindingContext = this.BindingContext;
            this.reflashTempletBNT.BindingContext = this.BindingContext;
            this.setSumTable.BindingContext = this.BindingContext;
            this.IsGetTelecomDatacheckBox.BindingContext = this.BindingContext;
            this.IsGetMobileDatacheckBox.BindingContext = this.BindingContext;
            this.IsGetUnicomDatacheckBox.BindingContext = this.BindingContext;
            this.IsGetNotRequireStationcheckBox.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static outputReport _outputReport;
        
        internal static outputReport outputReport {
            get {
                return _outputReport;
            }
            set {
                if ((_outputReport == null)) {
                    _outputReport = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
